version: '3.8'

services:
  frontend:
    build: frontend/
    image: ghcr.io/warehog/podej-dalej/pd-frontend:develop

  backend:
    build: backend/
    image: ghcr.io/warehog/podej-dalej/pd-backend:develop
    ports:
      - 3001:3000
    environment:
      RAILS_ENV: development
      DB_ADAPTER: postgresql
      DB_HOST: db
      DB_NAME: db_name
      DB_USER: db_user
      DB_PASS: db_pass
      STORAGE_SERVICE: local
      MINIO_BUCKET: default
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY_ID: administrator
      MINIO_SECRET_ACCESS_KEY: administrator
    depends_on:
      - migrate

  migrate:
    build: backend/
    image: ghcr.io/warehog/podej-dalej/pd-backend:develop
    entrypoint: >
      /bin/sh -c "
        rails db:migrate;
      "
    environment:
      RAILS_ENV: development
      DB_ADAPTER: postgresql
      DB_HOST: db
      DB_NAME: db_name
      DB_USER: db_user
      DB_PASS: db_pass
      STORAGE_SERVICE: local
      MINIO_BUCKET: default
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY_ID: administrator
      MINIO_SECRET_ACCESS_KEY: administrator
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      DB_ADAPTER: postgresql
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  proxy:
    image: caddy
    ports:
      - 6776:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  minio:
    image: minio/minio
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - 'minio:/data'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=administrator
      - MINIO_ROOT_PASSWORD=administrator
      - MINIO_DEFAULT_BUCKETS=default
  
  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 4;
      /usr/bin/mc alias set myminio http://minio:9000 administrator administrator;
      /usr/bin/mc mb myminio/default;
      exit 0;
      "

volumes:
  db_data:
  minio:
